2020-06-13 11:30:38,320 - pyngrok.process - INFO - ngrok process starting: 7860
2020-06-13 11:30:39,721 - pyngrok.process - INFO - ngrok process has started: http://127.0.0.1:4040
2020-06-13 11:30:44,412 - src.bot_agent - INFO - reset webhook
 {"ok":true,"result":true,"description":"Webhook was set"}
2020-06-13 11:30:44,489 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-13 11:30:45,022 - __main__ - ERROR - Exception on /hook [POST]
Traceback (most recent call last):
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<ipython-input-1-39e676d71324>", line 79, in webhook_handler
    text = update.message.text
AttributeError: 'NoneType' object has no attribute 'text'
2020-06-13 11:30:45,031 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:45] "[35m[1mPOST /hook HTTP/1.1[0m" 500 -
2020-06-13 11:30:45,642 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:45,642 - src.bot_agent - INFO - webhook - get message - /help
2020-06-13 11:30:47,738 - src.bot_agent - INFO - help_handler - get help
2020-06-13 11:30:47,739 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:47] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:48,354 - __main__ - ERROR - Exception on /hook [POST]
Traceback (most recent call last):
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<ipython-input-1-39e676d71324>", line 79, in webhook_handler
    text = update.message.text
AttributeError: 'NoneType' object has no attribute 'text'
2020-06-13 11:30:48,357 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:48] "[35m[1mPOST /hook HTTP/1.1[0m" 500 -
2020-06-13 11:30:48,638 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,639 - src.bot_agent - INFO - webhook - get message - /tool
2020-06-13 11:30:48,644 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,644 - src.bot_agent - INFO - webhook - get message - 1111
2020-06-13 11:30:48,649 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,650 - src.bot_agent - INFO - webhook - get message - ±ÀÂËªÑ²¼
2020-06-13 11:30:48,912 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,912 - src.bot_agent - INFO - webhook - get message - id 123
2020-06-13 11:30:48,917 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,918 - src.bot_agent - INFO - webhook - get message - id 2222
2020-06-13 11:30:48,921 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,922 - src.bot_agent - INFO - webhook - get message - ±ÀÂËªÑ²¼
2020-06-13 11:30:48,931 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,932 - src.bot_agent - INFO - webhook - get message - ·j´M¬ÛÃöªºªÑ²¼
2020-06-13 11:30:48,948 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,948 - src.bot_agent - INFO - webhook - get message - ±ÀÂËªÑ²¼
2020-06-13 11:30:48,959 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,960 - src.bot_agent - INFO - webhook - get message - ¨ä¥L¤H¤]³ßÅw
2020-06-13 11:30:48,964 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,965 - src.bot_agent - INFO - webhook - get message - id 154
2020-06-13 11:30:48,978 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,983 - src.bot_agent - INFO - webhook - get message - ±ÀÂËªÑ²¼
2020-06-13 11:30:48,989 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:48,990 - src.bot_agent - INFO - webhook - get message - id 1522
2020-06-13 11:30:49,000 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:49,001 - src.bot_agent - INFO - webhook - get message - ¨ä¥L¤H¤]³ßÅw
2020-06-13 11:30:49,014 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:49,014 - src.bot_agent - INFO - webhook - get message - id 123
2020-06-13 11:30:49,031 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:49,031 - src.bot_agent - INFO - webhook - get message - id 2333
2020-06-13 11:30:49,048 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:49,048 - src.bot_agent - INFO - webhook - get message - id 2222
2020-06-13 11:30:49,053 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:49,054 - src.bot_agent - INFO - webhook - get message - ±ÀÂËªÑ²¼
2020-06-13 11:30:49,077 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:49,077 - src.bot_agent - INFO - webhook - get message - id 134
2020-06-13 11:30:49,080 - src.bot_agent - INFO - ========================================
2020-06-13 11:30:49,081 - src.bot_agent - INFO - webhook - get message - aaa
2020-06-13 11:30:49,115 - src.bot_agent - INFO - tool_handler - get tool
2020-06-13 11:30:49,116 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:49] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:49,822 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2020-06-13 11:30:49,827 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:49] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:49,835 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2020-06-13 11:30:49,868 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:49] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:50,081 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2020-06-13 11:30:50,088 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:50] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:50,247 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2020-06-13 11:30:50,249 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2020-06-13 11:30:50,251 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2020-06-13 11:30:50,255 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:50] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:50,260 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:50] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:50,262 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2020-06-13 11:30:50,266 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:50] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:50,268 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2020-06-13 11:30:50,270 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2020-06-13 11:30:50,298 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2020-06-13 11:30:50,328 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:50] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:50,334 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:50] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:50,338 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:50] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:50,348 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:50] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:51,344 - src.bot_agent - ERROR - Update "{'update_id': 100568625, 'message': {'message_id': 287, 'date': 1592018771, 'chat': {'id': 1021237984, 'type': 'private', 'first_name': '¨|½å', 'last_name': 'ªL'}, 'text': 'id 2222', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1021237984, 'first_name': '¨|½å', 'is_bot': False, 'last_name': 'ªL', 'language_code': 'zh-hans'}}, '_effective_message': {'message_id': 287, 'date': 1592018771, 'chat': {'id': 1021237984, 'type': 'private', 'first_name': '¨|½å', 'last_name': 'ªL'}, 'text': 'id 2222', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1021237984, 'first_name': '¨|½å', 'is_bot': False, 'last_name': 'ªL', 'language_code': 'zh-hans'}}}" caused error "Task <Task pending coro=<Application.run_async() running at D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\prompt_toolkit\application\application.py:778> cb=[_run_until_complete_cb() at D:\Users\aaron\anaconda3\envs\fintech\lib\asyncio\base_events.py:158]> got Future <Task pending coro=<KeyProcessor._start_timeout.<locals>.wait() running at D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\prompt_toolkit\key_binding\key_processor.py:406> wait_for=<Future cancelled>> attached to a different loop"
2020-06-13 11:30:51,882 - src.bot_agent - INFO - error_handler - get error
2020-06-13 11:30:51,883 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:51] "[37mPOST /hook HTTP/1.1[0m" 200 -
2020-06-13 11:30:52,980 - __main__ - ERROR - Exception on /hook [POST]
Traceback (most recent call last):
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<ipython-input-1-39e676d71324>", line 79, in webhook_handler
    text = update.message.text
AttributeError: 'NoneType' object has no attribute 'text'
2020-06-13 11:30:52,983 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:30:52] "[35m[1mPOST /hook HTTP/1.1[0m" 500 -
2020-06-13 11:31:01,708 - __main__ - ERROR - Exception on /hook [POST]
Traceback (most recent call last):
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\aaron\anaconda3\envs\fintech\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<ipython-input-1-39e676d71324>", line 79, in webhook_handler
    text = update.message.text
AttributeError: 'NoneType' object has no attribute 'text'
2020-06-13 11:31:01,711 - werkzeug - INFO - 127.0.0.1 - - [13/Jun/2020 11:31:01] "[35m[1mPOST /hook HTTP/1.1[0m" 500 -
